create table ADMIN (
	ad_id INT,
	ad_first_name VARCHAR(50),
	ad_last_name VARCHAR(50),
	ad_user_name VARCHAR(50),
	ad_email VARCHAR(50)
);
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (1, 'Rickie', 'Shurmore', 'rshurmore0', 'rshurmore0@icq.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (2, 'Louise', 'Mitcham', 'lmitcham1', 'lmitcham1@qq.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (3, 'Royce', 'Durtnall', 'rdurtnall2', 'rdurtnall2@berkeley.edu');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (4, 'Berti', 'Portchmouth', 'bportchmouth3', 'bportchmouth3@cdc.gov');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (5, 'Austin', 'Le Franc', 'alefranc4', 'alefranc4@auda.org.au');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (6, 'Shela', 'Sercombe', 'ssercombe5', 'ssercombe5@twitter.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (7, 'Gibb', 'Parcells', 'gparcells6', 'gparcells6@domainmarket.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (8, 'Lara', 'Palethorpe', 'lpalethorpe7', 'lpalethorpe7@mtv.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (9, 'Marty', 'O''Geaney', 'mogeaney8', 'mogeaney8@wix.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (10, 'Hewet', 'Salmons', 'hsalmons9', 'hsalmons9@sitemeter.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (11, 'Renae', 'De Goey', 'rdegoeya', 'rdegoeya@mozilla.org');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (12, 'Gnni', 'Mundle', 'gmundleb', 'gmundleb@harvard.edu');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (13, 'Prudence', 'Brockelsby', 'pbrockelsbyc', 'pbrockelsbyc@taobao.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (14, 'Colman', 'Ulrik', 'culrikd', 'culrikd@slideshare.net');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (15, 'Doralia', 'Phippin', 'dphippine', 'dphippine@google.es');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (16, 'Shawn', 'McFeate', 'smcfeatef', 'smcfeatef@pen.io');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (17, 'Melessa', 'Edgehill', 'medgehillg', 'medgehillg@bloomberg.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (18, 'Gabby', 'Chave', 'gchaveh', 'gchaveh@eepurl.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (19, 'Olive', 'Lemmen', 'olemmeni', 'olemmeni@godaddy.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (20, 'Hedda', 'Le Provost', 'hleprovostj', 'hleprovostj@si.edu');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (21, 'Tedda', 'Devey', 'tdeveyk', 'tdeveyk@comcast.net');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (22, 'Susann', 'Eirwin', 'seirwinl', 'seirwinl@quantcast.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (23, 'Donielle', 'Gosnall', 'dgosnallm', 'dgosnallm@angelfire.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (24, 'Hercules', 'Dockreay', 'hdockreayn', 'hdockreayn@unc.edu');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (25, 'Katinka', 'McOrkill', 'kmcorkillo', 'kmcorkillo@cbslocal.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (26, 'Reid', 'Wadesworth', 'rwadesworthp', 'rwadesworthp@nyu.edu');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (27, 'Mattheus', 'Vasilchenko', 'mvasilchenkoq', 'mvasilchenkoq@chron.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (28, 'Tamarah', 'Rowan', 'trowanr', 'trowanr@toplist.cz');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (29, 'Karel', 'Burges', 'kburgess', 'kburgess@geocities.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (30, 'Shanna', 'Trounson', 'strounsont', 'strounsont@stanford.edu');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (31, 'Cecily', 'Paton', 'cpatonu', 'cpatonu@auda.org.au');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (32, 'Florrie', 'Knappen', 'fknappenv', 'fknappenv@icio.us');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (33, 'Minette', 'McUre', 'mmcurew', 'mmcurew@woothemes.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (34, 'Kippy', 'Longstreeth', 'klongstreethx', 'klongstreethx@guardian.co.uk');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (35, 'Hube', 'Catterall', 'hcatterally', 'hcatterally@businessinsider.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (36, 'Natalie', 'Prangley', 'nprangleyz', 'nprangleyz@gnu.org');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (37, 'Vania', 'Garbert', 'vgarbert10', 'vgarbert10@google.com.hk');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (38, 'Joana', 'Haskew', 'jhaskew11', 'jhaskew11@state.gov');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (39, 'Douglass', 'Lyndon', 'dlyndon12', 'dlyndon12@g.co');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (40, 'Forester', 'Wandrach', 'fwandrach13', 'fwandrach13@economist.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (41, 'Suzanne', 'MacCallum', 'smaccallum14', 'smaccallum14@php.net');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (42, 'Georgine', 'Geistbeck', 'ggeistbeck15', 'ggeistbeck15@mysql.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (43, 'Jennee', 'Hendriksen', 'jhendriksen16', 'jhendriksen16@bigcartel.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (44, 'Karoline', 'Alsopp', 'kalsopp17', 'kalsopp17@newyorker.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (45, 'Auria', 'Beange', 'abeange18', 'abeange18@abc.net.au');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (46, 'Babara', 'Buckell', 'bbuckell19', 'bbuckell19@dmoz.org');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (47, 'Welsh', 'Lodin', 'wlodin1a', 'wlodin1a@hc360.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (48, 'Christi', 'Klulik', 'cklulik1b', 'cklulik1b@1688.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (49, 'Gerianne', 'Bamlett', 'gbamlett1c', 'gbamlett1c@nymag.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (50, 'Arney', 'Scimonelli', 'ascimonelli1d', 'ascimonelli1d@seesaa.net');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (51, 'Bronny', 'Noseworthy', 'bnoseworthy1e', 'bnoseworthy1e@aol.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (52, 'Drusie', 'Fernier', 'dfernier1f', 'dfernier1f@ocn.ne.jp');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (53, 'Legra', 'Ashbolt', 'lashbolt1g', 'lashbolt1g@mit.edu');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (54, 'Chase', 'Seleway', 'cseleway1h', 'cseleway1h@tinypic.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (55, 'Sheffield', 'Bramhall', 'sbramhall1i', 'sbramhall1i@imageshack.us');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (56, 'Jacklyn', 'Eckersley', 'jeckersley1j', 'jeckersley1j@ucoz.ru');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (57, 'Alic', 'Sille', 'asille1k', 'asille1k@hostgator.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (58, 'Brook', 'Lindhe', 'blindhe1l', 'blindhe1l@feedburner.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (59, 'Whittaker', 'Persse', 'wpersse1m', 'wpersse1m@soundcloud.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (60, 'Heda', 'D''Andrea', 'hdandrea1n', 'hdandrea1n@house.gov');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (61, 'Brose', 'Hanny', 'bhanny1o', 'bhanny1o@webmd.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (62, 'Tabb', 'Critoph', 'tcritoph1p', 'tcritoph1p@msu.edu');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (63, 'Joscelin', 'Harmes', 'jharmes1q', 'jharmes1q@ebay.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (64, 'Merle', 'Delgardo', 'mdelgardo1r', 'mdelgardo1r@home.pl');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (65, 'Kenneth', 'Freake', 'kfreake1s', 'kfreake1s@weibo.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (66, 'Caz', 'Stack', 'cstack1t', 'cstack1t@nsw.gov.au');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (67, 'Guilbert', 'Harrild', 'gharrild1u', 'gharrild1u@vkontakte.ru');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (68, 'Elisha', 'Filipyev', 'efilipyev1v', 'efilipyev1v@themeforest.net');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (69, 'Oralie', 'Goublier', 'ogoublier1w', 'ogoublier1w@yelp.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (70, 'Omero', 'Guirard', 'oguirard1x', 'oguirard1x@utexas.edu');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (71, 'Tisha', 'Reek', 'treek1y', 'treek1y@smh.com.au');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (72, 'Davida', 'Klainer', 'dklainer1z', 'dklainer1z@cnn.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (73, 'Eberto', 'Paolino', 'epaolino20', 'epaolino20@ca.gov');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (74, 'Jeremias', 'Maleck', 'jmaleck21', 'jmaleck21@t-online.de');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (75, 'Noah', 'Luscombe', 'nluscombe22', 'nluscombe22@discovery.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (76, 'Pearce', 'Camus', 'pcamus23', 'pcamus23@github.io');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (77, 'Blondell', 'Szantho', 'bszantho24', 'bszantho24@bbb.org');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (78, 'Mechelle', 'Riatt', 'mriatt25', 'mriatt25@businessweek.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (79, 'Anne-corinne', 'Chaise', 'achaise26', 'achaise26@etsy.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (80, 'Maudie', 'Kike', 'mkike27', 'mkike27@usa.gov');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (81, 'Weider', 'Allicock', 'wallicock28', 'wallicock28@scribd.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (82, 'Rocky', 'Lanceley', 'rlanceley29', 'rlanceley29@wix.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (83, 'El', 'Hatchard', 'ehatchard2a', 'ehatchard2a@chron.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (84, 'Nial', 'Volet', 'nvolet2b', 'nvolet2b@meetup.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (85, 'Carolina', 'Bernardy', 'cbernardy2c', 'cbernardy2c@amazon.co.jp');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (86, 'Quintus', 'Kilfedder', 'qkilfedder2d', 'qkilfedder2d@nymag.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (87, 'Honoria', 'Hellin', 'hhellin2e', 'hhellin2e@stumbleupon.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (88, 'Sammy', 'Glanert', 'sglanert2f', 'sglanert2f@dailymotion.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (89, 'Alexandr', 'Stenton', 'astenton2g', 'astenton2g@meetup.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (90, 'Dori', 'Wisson', 'dwisson2h', 'dwisson2h@gov.uk');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (91, 'Sully', 'Ingerith', 'singerith2i', 'singerith2i@unicef.org');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (92, 'Nonie', 'O''Brian', 'nobrian2j', 'nobrian2j@engadget.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (93, 'Huberto', 'Stut', 'hstut2k', 'hstut2k@cdc.gov');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (94, 'Sloan', 'Giacubbo', 'sgiacubbo2l', 'sgiacubbo2l@t-online.de');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (95, 'Gram', 'Cristofolo', 'gcristofolo2m', 'gcristofolo2m@usatoday.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (96, 'Phelia', 'Summerfield', 'psummerfield2n', 'psummerfield2n@liveinternet.ru');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (97, 'Lonnie', 'Wren', 'lwren2o', 'lwren2o@zdnet.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (98, 'Norah', 'Bonifacio', 'nbonifacio2p', 'nbonifacio2p@yahoo.co.jp');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (99, 'Otis', 'Guppy', 'oguppy2q', 'oguppy2q@dell.com');
insert into ADMIN (ad_id, ad_first_name, ad_last_name, ad_user_name, ad_email) values (100, 'Saw', 'Siviter', 'ssiviter2r', 'ssiviter2r@loc.gov');
