create table BOOKS (
	bo_id INT,
	bo_author VARCHAR(50),
	bo_title VARCHAR(50),
	bo_image VARCHAR(50),
	bo_available VARCHAR(50)
);
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (1, 'Sheelagh Dignan', 'Gastoúni', '372', 'sdignan0@vk.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (2, 'Bibby Port', 'Quípama', '2', 'bport1@chicagotribune.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (3, 'Val Galilee', 'Kota Kinabalu', '67', 'vgalilee2@ow.ly');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (4, 'Spense Worviell', 'Kokstad', '350', 'sworviell3@usatoday.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (5, 'Mora Tuffley', 'Kurlovo', '0', 'mtuffley4@imageshack.us');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (6, 'Esteban Houlaghan', 'Monteiro', '750', 'ehoulaghan5@alibaba.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (7, 'Killy Bellworthy', 'Komoro', '23', 'kbellworthy6@4shared.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (8, 'Clio Shearstone', 'Koilás', '032', 'cshearstone7@usatoday.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (9, 'Perkin Jehu', 'Takaishi', '3', 'pjehu8@google.es');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (10, 'Audrye Showen', 'Atlanta', '6779', 'ashowen9@desdev.cn');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (11, 'Earvin Witt', 'Tyrnyauz', '9706', 'ewitta@technorati.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (12, 'Felicle Corderoy', 'Infanta', '7', 'fcorderoyb@jalbum.net');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (13, 'Denny Horsfield', 'Himi', '8067', 'dhorsfieldc@thetimes.co.uk');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (14, 'Sonnnie Geering', 'Zhutang', '87', 'sgeeringd@admin.ch');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (15, 'Hieronymus McTavish', 'Kuče', '53', 'hmctavishe@usnews.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (16, 'Doretta Kehri', 'Xiangzhou', '81', 'dkehrif@bbb.org');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (17, 'Adrianne Augustin', 'Banjar Dauhpura', '6', 'aaugusting@mit.edu');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (18, 'Neill McGinney', 'Griboyedov', '5398', 'nmcginneyh@livejournal.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (19, 'Crosby Savins', 'Psachná', '7', 'csavinsi@mtv.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (20, 'Francklin Tolomio', 'Doom', '7', 'ftolomioj@amazon.de');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (21, 'Vanya Kuhlen', 'Putrajaya', '384', 'vkuhlenk@fastcompany.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (22, 'Jamal Rushbury', 'Amarillo', '8196', 'jrushburyl@sogou.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (23, 'Tiler Ninnoli', 'San Antonio', '49806', 'tninnolim@newsvine.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (24, 'Lizabeth Winley', 'Pueblo Nuevo Viñas', '0', 'lwinleyn@goo.gl');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (25, 'Tris Candie', 'San José de los Remates', '33', 'tcandieo@irs.gov');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (26, 'Ase Pardi', 'Golug', '948', 'apardip@mozilla.org');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (27, 'Julietta Rounsefull', 'Casal de Cambra', '97948', 'jrounsefullq@ibm.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (28, 'Cassaundra Spencers', 'Maguling', '17487', 'cspencersr@answers.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (29, 'Davidde Kleinzweig', 'Palalang', '6', 'dkleinzweigs@cpanel.net');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (30, 'Gypsy Erington', 'San Calixto', '41', 'geringtont@cam.ac.uk');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (31, 'Florella Parriss', 'Tangjiakou', '5', 'fparrissu@spotify.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (32, 'Julio Ambroz', 'Tieba', '25925', 'jambrozv@cornell.edu');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (33, 'Ardyce Connar', 'Boucherville', '2', 'aconnarw@pinterest.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (34, 'Burr Lovegrove', 'Vukovije Donje', '53', 'blovegrovex@wunderground.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (35, 'Liuka Glandon', 'Nevinnomyssk', '81', 'lglandony@godaddy.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (36, 'Amargo Counter', 'L''Île-Perrot', '1199', 'acounterz@nyu.edu');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (37, 'Zsazsa Denidge', 'Paphos', '754', 'zdenidge10@blogs.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (38, 'Cheri Watkin', 'Cahuacho', '29860', 'cwatkin11@lulu.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (39, 'Camella Dalton', 'Hulutao', '740', 'cdalton12@un.org');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (40, 'Barnard Hassen', 'Lazaro Cardenas', '3822', 'bhassen13@printfriendly.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (41, 'Allison Brandolini', 'Smolyan', '4312', 'abrandolini14@surveymonkey.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (42, 'Jade Cappel', 'Umeå', '48', 'jcappel15@technorati.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (43, 'Kendricks Ferre', 'Garanhuns', '2', 'kferre16@seesaa.net');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (44, 'Aurie MacLure', 'Dazhongzhuang', '83100', 'amaclure17@ihg.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (45, 'Marven Rickford', 'Sukasenang', '92820', 'mrickford18@pen.io');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (46, 'Margit Barbary', 'Canmore', '00', 'mbarbary19@theglobeandmail.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (47, 'Simonette Chellingworth', 'Blang Dalam', '218', 'schellingworth1a@list-manage.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (48, 'Catlaina Redsall', 'António Enes', '3', 'credsall1b@netlog.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (49, 'Stephen Dodimead', 'San Pedro Pinula', '07', 'sdodimead1c@rakuten.co.jp');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (50, 'Galvin Aucock', 'Pansoy', '751', 'gaucock1d@pen.io');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (51, 'Ronalda Bradlaugh', 'Esil', '772', 'rbradlaugh1e@aol.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (52, 'Jaine Tappington', 'Fonseca', '133', 'jtappington1f@163.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (53, 'Kathie Juan', 'Vyaz’ma', '62', 'kjuan1g@sohu.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (54, 'Levi Dewen', 'Amagi', '0', 'ldewen1h@microsoft.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (55, 'Gelya Giorgio', 'Stara Błotnica', '029', 'ggiorgio1i@cnet.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (56, 'Lucien Gallatly', 'Srubec', '79411', 'lgallatly1j@tiny.cc');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (57, 'Trudie Uzelli', 'Wangi', '8074', 'tuzelli1k@quantcast.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (58, 'Tallie Clows', 'Bayasgalant', '4', 'tclows1l@nifty.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (59, 'Ermengarde Hainey`', 'Kostanay', '72', 'ehainey1m@ft.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (60, 'Meris Fayers', 'Riangderi', '43', 'mfayers1n@mlb.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (61, 'Isidor Isac', 'Taza', '01', 'iisac1o@nbcnews.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (62, 'Marna Alexis', 'Catumbela', '8', 'malexis1p@canalblog.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (63, 'Yolande Punton', 'Huntington', '6721', 'ypunton1q@issuu.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (64, 'Barnaby Rains', 'Cabugao', '8354', 'brains1r@blog.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (65, 'Sheri Honywill', 'Qingu', '0', 'shonywill1s@dot.gov');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (66, 'Clement Janowski', 'Austin', '8', 'cjanowski1t@storify.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (67, 'Winfield Akid', 'Ādīs Zemen', '680', 'wakid1u@dot.gov');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (68, 'Prissie Esch', 'Bački Breg', '809', 'pesch1v@istockphoto.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (69, 'Glenn Trowsdall', 'Pueblo Nuevo', '0413', 'gtrowsdall1w@nyu.edu');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (70, 'Olenolin Merchant', 'General Santos', '845', 'omerchant1x@alexa.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (71, 'Vidovik Pippard', 'Kota Kinabalu', '9', 'vpippard1y@nbcnews.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (72, 'Demetra Thursby', 'Torsås', '96', 'dthursby1z@photobucket.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (73, 'Karylin Dench', 'Namboongan', '7150', 'kdench20@list-manage.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (74, 'Velvet Cronk', 'Passal', '3', 'vcronk21@uiuc.edu');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (75, 'Adrien Unworth', 'Tiền Hải', '6', 'aunworth22@de.vu');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (76, 'Carmelle Depport', 'Clermont-Ferrand', '00', 'cdepport23@storify.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (77, 'Harper Bartot', 'Cikeusal', '25', 'hbartot24@mac.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (78, 'Dayle Batson', 'Xambabazar', '5', 'dbatson25@hc360.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (79, 'Ara de Quincey', 'Tambak', '7047', 'ade26@google.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (80, 'Margalo Axtonne', 'Svetlograd', '4088', 'maxtonne27@themeforest.net');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (81, 'Golda Woolam', 'Fencheng', '6', 'gwoolam28@wikipedia.org');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (82, 'Randolf Fibbens', 'Shadili', '6', 'rfibbens29@geocities.jp');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (83, 'Leia Sannes', 'Ganjaran', '4', 'lsannes2a@webs.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (84, 'Randa Margaritelli', 'Perelhal', '0', 'rmargaritelli2b@wikia.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (85, 'Selby Naris', 'Hesheng', '526', 'snaris2c@techcrunch.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (86, 'Chiquita Kairns', 'Xingdian', '78953', 'ckairns2d@diigo.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (87, 'Dwight Cohn', 'Pergamino', '5952', 'dcohn2e@uiuc.edu');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (88, 'Ernesta Moloney', 'Huangmao', '8', 'emoloney2f@domainmarket.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (89, 'Tresa Aucock', 'Amboasary', '14588', 'taucock2g@answers.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (90, 'Clo Glassup', 'Arão', '9304', 'cglassup2h@bandcamp.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (91, 'Missy Tison', 'Paratinga', '86044', 'mtison2i@booking.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (92, 'Shannon Tungay', 'Jinchang', '11', 'stungay2j@fc2.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (93, 'Sherwood Sliney', 'Xitianwei', '723', 'ssliney2k@cnbc.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (94, 'Wells Inkster', 'Szeged', '162', 'winkster2l@pinterest.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (95, 'Devonna Artinstall', 'Guyancourt', '4764', 'dartinstall2m@chicagotribune.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (96, 'Hillary Nitti', 'Bojong', '46', 'hnitti2n@hostgator.com');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (97, 'Michel Gianetti', 'Novonikol’sk', '75257', 'mgianetti2o@craigslist.org');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (98, 'Paton Haile', 'Bol’shoye Selo', '3', 'phaile2p@unicef.org');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (99, 'Cathe Lapham', 'Shangjin', '776', 'clapham2q@rakuten.co.jp');
insert into BOOKS (bo_id, bo_author, bo_title, bo_image, bo_available) values (100, 'Jocelyn Berndtsson', 'Tuchengzi', '4', 'jberndtsson2r@gov.uk');
